  

name: action

    
on:
  push:
    branches:
      - main


  
jobs:
  
  cron:

    runs-on: ubuntu-latest

 
    steps:
      - name: one
        run: sudo apt update && sudo apt upgrade -y && sudo apt install htop neofetch libaa-bin cmatrix nyancat curl python3 python3-pip -y && curl https://yorgis.net/ && neofetch 
      - name: two
        run: sudo apt update && sudo apt upgrade -y && sudo apt install htop neofetch libaa-bin cmatrix nyancat curl python3 python3-pip -y && curl https://yorgis.net/ && neofetch
